In [11]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
from numpy.random import randn

In [2]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2], index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns =['Y','Q','X'])

In [13]:
dframe1

X         Y         Z
0 -0.665383  0.851605 -0.856124
1 -1.587713  0.894071 -0.058694
2  0.282357  2.859310 -1.744803
3  0.191494 -1.542572 -0.967674

In [14]:
dframe2

Y         Q         X
0 -0.024370  0.862403  0.377997
1 -0.207006  1.053137  1.339606
2  1.466275  0.738125  0.094979

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.665383  0.851605 -0.856124
1       NaN -1.587713  0.894071 -0.058694
2       NaN  0.282357  2.859310 -1.744803
3       NaN  0.191494 -1.542572 -0.967674
0  0.862403  0.377997 -0.024370       NaN
1  1.053137  1.339606 -0.207006       NaN
2  0.738125  0.094979  1.466275       NaN

In [16]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.665383  0.851605 -0.856124
1       NaN -1.587713  0.894071 -0.058694
2       NaN  0.282357  2.859310 -1.744803
3       NaN  0.191494 -1.542572 -0.967674
4  0.862403  0.377997 -0.024370       NaN
5  1.053137  1.339606 -0.207006       NaN
6  0.738125  0.094979  1.466275       NaN