In [1]:
import numpy as np
from numpy.random import randn

In [4]:
#numpy.where vercotrized version of expression x if condition else y

xarr = np.arange(1.1, 1.6, 0.1)
xarr

array([ 1.1,  1.2,  1.3,  1.4,  1.5])

In [6]:
yarr = np.arange(2.1, 2.6, 0.1)

In [7]:
cond = np.array([1,0,1,1,0])

In [10]:
result = [(x if c else y)
          for x,y,c in zip(xarr,yarr,cond)]
result

[1.1000000000000001,
 2.2000000000000002,
 1.3000000000000003,
 1.4000000000000004,
 2.5000000000000004]

In [19]:
#better: np.where()
np.where(cond,xarr,yarr)
#2nd and 3rd argument dont need both to be arrays,
#one or both can be a scalar. see examples below

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [15]:
arr = randn(4,4)
arr

array([[ 0.29518082,  0.11867132, -1.23701164,  0.66373232],
       [ 1.88612395,  2.43213913,  0.13661085, -0.71700718],
       [ 1.39728165,  0.05390224,  0.87375379, -0.13006605],
       [-1.94280483, -0.44758021, -1.39284327, -1.90601403]])

In [17]:
np.where(arr > 0, 2,-2)

array([[ 2,  2, -2,  2],
       [ 2,  2,  2, -2],
       [ 2,  2,  2, -2],
       [-2, -2, -2, -2]])

In [18]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        , -1.23701164,  2.        ],
       [ 2.        ,  2.        ,  2.        , -0.71700718],
       [ 2.        ,  2.        ,  2.        , -0.13006605],
       [-1.94280483, -0.44758021, -1.39284327, -1.90601403]])

In [23]:
#nested np.where()
cond1 = np.array([1,1,0])
cond2 = np.array([0,1,0])
np.where(cond1 & cond2, 0, np.where(cond1, 1, np.where(cond2, 2, 3)))

array([1, 0, 3])