In [3]:
import numpy as np
from numpy.random import randn

In [14]:
data = {i : randn() for i in range(7)}

In [15]:
%debug

> /home/reinka/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py(707)_input_request()
    706                 # re-raise KeyboardInterrupt, to truncate traceback
--> 707                 raise KeyboardInterrupt
    708             else:

ipdb> c


In [16]:
data?

In [17]:
np.*load*?

In [18]:
###numpy now


In [19]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [24]:
zeros_arr = np.zeros((3,6))
ones_arr = np.ones((4,4))
ones_arr

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [21]:
empty_arr = np.empty((2,2,2))
zeros_arr.shape
empty_arr.dtype

dtype('float64')

In [23]:
empty_arr.ndim

3

In [32]:
#takes anohter array and produces a ones array of same shape
np.ones_like(empty_arr)

array([[[ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]])

In [33]:
#identity matrix
np.eye(3,4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [35]:
#specifiy the data type of the array
arr1 = np.array([1,2,3],dtype=np.float64)
arr1

array([ 1.,  2.,  3.])

In [37]:
arr2 = np.array(arr1,dtype=np.int64)
arr2

array([1, 2, 3])

In [38]:
arr3 = arr1.astype(np.float64)
arr3

array([ 1.,  2.,  3.])

In [39]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype=(np.string_))

In [40]:
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

In [42]:
#use another's array dtype attribute for conversion:
numeric_strings.astype(arr1.dtype)

array([  1.25,  -9.6 ,  42.  ])

In [43]:
#operations between arrays and scalars

In [50]:
arr = np.array([[1,2,3],[4,5,6]],dtype=float)
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [51]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [52]:
arr-arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [53]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [54]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [19]:
arr = np.arange(10)

In [20]:
arr[5]

5

In [21]:
arr[5:8]

array([5, 6, 7])

In [22]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [23]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [26]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [28]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [7]:
arr_test = np.arange(7)

In [8]:
arr_test

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
test = arr_test

In [10]:
test

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
test[2:4]

array([2, 3])

In [12]:
slicees = test[2:4]

In [13]:
slicees

array([2, 3])

In [14]:
slicees[1]=12345

In [16]:
slicees

array([    2, 12345])

In [17]:
test

array([    0,     1,     2, 12345,     4,     5,     6])

In [24]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [30]:
arr2d[2]

array([7, 8, 9])

In [31]:
arr2d[0][2]

3

In [32]:
arr2d[0,2]

3

In [33]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [34]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
#make copy of arr3d[0] and assign it to new variable
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
#assign new values to arr3d[0], both scalars and arrays possible
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
#restore old values 
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[1,0]

array([7, 8, 9])

In [42]:
#INDEXING WITH SLICES

In [4]:
arr = range(10)

In [5]:
arr[1:6]

[1, 2, 3, 4, 5]

In [23]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [25]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [27]:
arr2d[1,:2]

array([4, 5])

In [28]:
copy = arr2d[:2,1:].copy()
arr2d[:2,1:] = 0

In [29]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [30]:
arr2d[:2,1:] = copy
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [37]:
data = randn(7,4)
data

array([[-1.14515948,  1.05130934,  0.02124966,  0.87120405],
       [-0.96449369, -1.80154492, -0.25352229,  0.97376526],
       [ 0.30056295, -0.0968516 , -0.63880422,  0.69534099],
       [-0.23773435, -0.54741096,  0.5112553 ,  0.71812008],
       [-1.09015295,  0.23941611, -0.42201002, -1.24960633],
       [ 0.18223401,  1.43585816,  0.38806145,  0.34371732],
       [ 1.96040635, -0.29432462,  0.99571463,  0.35719941]])

In [38]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [41]:
data[names == 'Bob']

array([[-1.14515948,  1.05130934,  0.02124966,  0.87120405],
       [-0.23773435, -0.54741096,  0.5112553 ,  0.71812008]])

In [44]:
data[names == 'Bob', 2:]

array([[ 0.02124966,  0.87120405],
       [ 0.5112553 ,  0.71812008]])

In [45]:
data[names == 'Bob', 3]

array([ 0.87120405,  0.71812008])

In [46]:
data[data < 0] = 0

In [47]:
data

array([[ 0.        ,  1.05130934,  0.02124966,  0.87120405],
       [ 0.        ,  0.        ,  0.        ,  0.97376526],
       [ 0.30056295,  0.        ,  0.        ,  0.69534099],
       [ 0.        ,  0.        ,  0.5112553 ,  0.71812008],
       [ 0.        ,  0.23941611,  0.        ,  0.        ],
       [ 0.18223401,  1.43585816,  0.38806145,  0.34371732],
       [ 1.96040635,  0.        ,  0.99571463,  0.35719941]])

In [48]:
data[names != 'Bob'] = 7
data

array([[ 0.        ,  1.05130934,  0.02124966,  0.87120405],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.        ,  0.5112553 ,  0.71812008],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ]])

In [1]:
#Fancy indexing

In [4]:
arr = np.empty((8,4))
arr

array([[  6.91786865e-310,   1.71302362e-316,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   2.14027814e+161,   5.12991416e+199,
          1.01849500e+248],
       [  1.16096643e-028,   5.30581644e+180,   4.31999742e-096,
          5.23081515e-143],
       [  2.22934962e+180,   4.27089936e-090,   2.25409012e+184,
          6.40300912e+170],
       [  4.30347747e-096,   9.08366791e+223,   4.25756448e-096,
          9.08366793e+223],
       [  1.70459660e+160,   1.28947672e+165,   2.08793683e-076,
          1.43402662e+161],
       [  7.11389294e-144,   1.16097020e-028,   6.37115240e-067,
          9.72245625e-067],
       [  3.85713715e-057,   2.65533089e-312,   1.24396006e-316,
          1.63041663e-322]])

In [5]:
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [6]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [7]:
arr[[-3,-4,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 4.,  4.,  4.,  4.],
       [ 1.,  1.,  1.,  1.]])

In [9]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [10]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [11]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [13]:
#np.ix_
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])