In [54]:
import numpy as np
from numpy.random import randn

In [49]:
#Unary funcs which take only 1 array as argument, like exp, sqrt:

In [50]:
arr = np.arange(10).reshape(2,5)

In [51]:
np.exp(arr)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
          2.00855369e+01,   5.45981500e+01],
       [  1.48413159e+02,   4.03428793e+02,   1.09663316e+03,
          2.98095799e+03,   8.10308393e+03]])

In [52]:
np.sqrt(arr)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ]])

In [53]:
#Binary ufuncc, like add or maximum:

In [57]:
x = randn(10)
x

array([ 0.88060038, -1.69756563, -1.08957976, -0.35446005, -0.9025174 ,
        1.68765204,  0.35120157,  0.60378664, -1.51653318, -0.44453318])

In [58]:
y = randn(10)
y

array([ 1.50429034,  0.04218664, -1.10887442, -1.21527054, -0.60975469,
       -1.42450214,  0.38989493,  0.26946129,  0.53593178, -0.59974989])

In [59]:
np.add(x,y)

array([ 2.38489072, -1.65537899, -2.19845418, -1.56973059, -1.51227209,
        0.26314991,  0.74109649,  0.87324793, -0.98060141, -1.04428307])

In [60]:
np.maximum(x,y)

array([ 1.50429034,  0.04218664, -1.08957976, -0.35446005, -0.60975469,
        1.68765204,  0.38989493,  0.60378664,  0.53593178, -0.44453318])

In [65]:
# np.modf(), returns frac and int part of floating point array

In [66]:
np.modf(x)

(array([ 0.88060038, -0.69756563, -0.08957976, -0.35446005, -0.9025174 ,
         0.68765204,  0.35120157,  0.60378664, -0.51653318, -0.44453318]),
 array([ 0., -1., -1., -0., -0.,  1.,  0.,  0., -1., -0.]))

In [68]:
#getting the frac part as array:
np.modf(x)[0]

array([ 0.88060038, -0.69756563, -0.08957976, -0.35446005, -0.9025174 ,
        0.68765204,  0.35120157,  0.60378664, -0.51653318, -0.44453318])

In [69]:
np.ceil(x)

array([ 1., -1., -1., -0., -0.,  2.,  1.,  1., -1., -0.])

In [70]:
x

array([ 0.88060038, -1.69756563, -1.08957976, -0.35446005, -0.9025174 ,
        1.68765204,  0.35120157,  0.60378664, -1.51653318, -0.44453318])

In [71]:
np.floor(x)

array([ 0., -2., -2., -1., -1.,  1.,  0.,  0., -2., -1.])

In [72]:
np.isnan(x)

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [73]:
np.isnan(x) == True

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [77]:
#find out if there is any NaN element within the array
np.isnan(x).any()

False

In [78]:
np.divide(x,y)

array([  0.58539257, -40.23941416,   0.98259977,   0.29167172,
         1.48013194,  -1.18473114,   0.90075952,   2.24071753,
        -2.82971312,   0.74119761])

In [79]:
np.floor_divide(x,y)

array([  0., -41.,   0.,   0.,   1.,  -2.,   0.,   2.,  -3.,   0.])

In [80]:
np.mod(x,y)

array([ 0.88060038,  0.03208656, -1.08957976, -0.35446005, -0.29276271,
       -1.16135223,  0.35120157,  0.06486406,  0.09126215, -0.44453318])

In [81]:
x

array([ 0.88060038, -1.69756563, -1.08957976, -0.35446005, -0.9025174 ,
        1.68765204,  0.35120157,  0.60378664, -1.51653318, -0.44453318])

In [82]:
y

array([ 1.50429034,  0.04218664, -1.10887442, -1.21527054, -0.60975469,
       -1.42450214,  0.38989493,  0.26946129,  0.53593178, -0.59974989])

In [83]:
np.greater_equal(x,y)

array([False, False,  True,  True, False,  True, False,  True, False,  True], dtype=bool)

In [85]:
y[np.greater_equal(x,y)]

array([-1.10887442, -1.21527054, -1.42450214,  0.26946129, -0.59974989])

In [89]:
x[np.greater_equal(x,y)]

array([-1.08957976, -0.35446005,  1.68765204,  0.60378664, -0.44453318])

In [90]:
np.not_equal(x,y)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)