In [1]:
import numpy as np
from numpy.random import randn

In [10]:
arr = randn(5,4)
arr

array([[-0.4449094 , -0.27454144, -1.41374458, -0.36221596],
       [ 0.62550649, -0.00301547, -0.92143234, -0.70474878],
       [-0.15533934,  1.13548111,  0.9088844 ,  1.11962181],
       [ 0.55402499, -0.14266786, -1.29246793,  0.02752355],
       [ 0.80935286,  1.0366692 ,  1.18354798, -0.99913814]])

In [4]:
arr.mean()

-0.09320110929581131

In [5]:
arr.sum()

-1.8640221859162263

In [13]:
arr.mean(1) #equal to arr.mean(axis=1)

array([-0.62385285, -0.25092252,  0.752162  , -0.21339681,  0.50760798])

In [14]:
arr.sum(0)

array([ 1.38863559,  1.75192554, -1.53521246, -0.91895751])

In [27]:
arr[:2,:1].sum()

0.18059708628473831

In [25]:
arr.cumsum(0)

array([[-0.4449094 , -0.27454144, -1.41374458, -0.36221596],
       [ 0.18059709, -0.27755691, -2.33517692, -1.06696474],
       [ 0.02525775,  0.85792421, -1.42629252,  0.05265707],
       [ 0.57928273,  0.71525634, -2.71876045,  0.08018062],
       [ 1.38863559,  1.75192554, -1.53521246, -0.91895751]])

In [26]:
arr.cumsum(1)

array([[-0.4449094 , -0.71945084, -2.13319542, -2.49541138],
       [ 0.62550649,  0.62249101, -0.29894132, -1.0036901 ],
       [-0.15533934,  0.98014177,  1.88902617,  3.00864798],
       [ 0.55402499,  0.41135713, -0.8811108 , -0.85358725],
       [ 0.80935286,  1.84602206,  3.02957004,  2.0304319 ]])

In [28]:
arr.cumsum()

array([-0.4449094 , -0.71945084, -2.13319542, -2.49541138, -1.8699049 ,
       -1.87292037, -2.7943527 , -3.49910148, -3.65444082, -2.51895971,
       -1.61007531, -0.4904535 ,  0.06357149, -0.07909637, -1.3715643 ,
       -1.34404074, -0.53468788,  0.50198131,  1.6855293 ,  0.68639116])