In [2]:
import numpy as np

In [3]:
#fancy indexing

In [4]:
arr = np.arange(35).reshape(7,5)

In [5]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [6]:
arr[np.ix_([2,5,4,3,6],[0,3,4,1,2])]

array([[10, 13, 14, 11, 12],
       [25, 28, 29, 26, 27],
       [20, 23, 24, 21, 22],
       [15, 18, 19, 16, 17],
       [30, 33, 34, 31, 32]])

In [11]:
index = np.array([1,2,3,4,5,6,7])
index

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
index == '1'

/home/reinka/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if __name__ == '__main__':


False

In [13]:
index == 1

array([ True, False, False, False, False, False, False], dtype=bool)

In [14]:
arr[index==1]

array([[0, 1, 2, 3, 4]])

In [26]:
arr[(index==2) | (index==3)]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
arr[index==4, 3:]

array([[18, 19]])

In [31]:
arr[[index==4, index==5]]

/home/reinka/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 1; dimension is 5 but corresponding boolean dimension is 7
  if __name__ == '__main__':


array([19])

In [33]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [35]:
arr[3:, 3:]

array([[18, 19],
       [23, 24],
       [28, 29],
       [33, 34]])

In [36]:
row = index
column = np.array([1,2,3,4,5])