In [1]:
import numpy as np
from numpy.random import randn

In [3]:
arr = randn(8)
arr

array([ 0.94462999, -0.51610481, -1.19878754,  0.98303354, -1.30771471,
        1.04535115,  0.33353521, -0.57585198])

In [5]:
arr.sort()
arr

array([-1.30771471, -1.19878754, -0.57585198, -0.51610481,  0.33353521,
        0.94462999,  0.98303354,  1.04535115])

In [8]:
#multidim sorting

arr = randn(8,5)
arr

array([[-0.26285551,  0.32788738,  1.20666862,  0.39473381,  0.38575451],
       [-0.68686896,  0.06374782,  0.19799065,  1.14768934, -1.72527726],
       [ 0.19034064,  0.15666296,  0.84946818,  0.62525914,  0.39007472],
       [ 0.44412147, -1.23399787,  0.53493187, -1.26954935,  0.89788862],
       [ 1.36273811,  0.96482786, -1.09313442,  0.40226502,  0.17069883],
       [ 0.71730652,  0.91871887,  1.85197411, -0.13265132,  0.64801251],
       [-0.49392932,  0.40280284,  0.49645598, -1.29478491,  1.0978576 ],
       [-0.16019191, -0.58470235,  0.4038061 ,  0.51960363,  0.6560959 ]])

In [7]:
arr.sort(1)
arr

array([[-0.85933775, -0.79285241, -0.38018733,  0.48238348,  0.9597971 ],
       [-1.1212501 , -1.00130204, -0.66263212,  0.17441706,  1.50970031],
       [-1.16626863, -1.15928607, -0.94085917,  1.04499363,  2.57129954],
       [-2.29819756, -1.86340848, -0.03575005,  0.38130802,  0.4933896 ],
       [-1.55363471, -1.08171968, -0.34297596,  0.71701742,  0.79445051],
       [-0.81049747, -0.30039284,  0.00267925,  0.02919668,  1.71374468],
       [-1.12029087, -0.47117391,  0.31340286,  0.7093667 ,  1.78991189],
       [-1.53238139, -1.27593869,  0.45229649,  0.83371424,  0.86505159]])

In [9]:
large_arr = randn(1000)

In [10]:
large_arr.sort()

In [11]:
large_arr[int(0.05*len(large_arr))] #5% quantile

-1.5694611027002827