In [1]:
import numpy as np
from numpy.random import randn

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [3]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='|S4')

In [4]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [7]:
np.unique(ints)

array([1, 2, 3, 4])

In [10]:
#python alternative:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [9]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [11]:
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

In [17]:
np.where(np.in1d(values,[2,3,6]),values,0)

array([6, 0, 0, 3, 2, 0, 6])

In [18]:
values[np.in1d(values,[2,3,6])]

array([6, 3, 2, 6])

In [20]:
#computes sorted union of elements
np.union1d(values,ints)

array([0, 1, 2, 3, 4, 5, 6])

In [22]:
#elements in x that are not in y
np.setdiff1d(ints,values)

array([1, 4])

In [23]:
#elements that are in either of the arrays, but not both
np.setxor1d(ints,values)

array([0, 1, 4, 5, 6])